export const AUTH_METHOD = {
  FACIAL: 'FACIAL',
  MANUAL: 'MANUAL',
  BOTH: 'BOTH',
};

export const CATEGORIA_RESIDUO = {
  PLASTICO: 'PLASTICO',
  CARTON: 'CARTON',
  VIDRIO: 'VIDRIO',
  ORGANICO: 'ORGANICO',
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
};
